<?php
bolt_decrypt( __FILE__ , 'CWRhPY'); return 0;
##!!!##BwdrXmpicG1eYGIdPm1tWUpsYWJpcDgHB3JwYh1GaWlyamZrXnFiWUFecV5fXnBiWUJpbG5yYmtxWUNeYHFsb2ZicFlFXnBDXmBxbG92OAdycGIdRmlpcmpma15xYllBXnFeX15wYllCaWxucmJrcVlKbGFiaTgHB2BpXnBwHU1eYGheZGJQYm9zZmBiHWJ1cWJrYXAdSmxhYmkHeAcdHR0dcnBiHUVecENeYHFsb3Y4Bx0dHR1tb2xxYmBxYmEdIXFeX2liHTodJG1eYGheZGJccGJvc2ZgYiQ4B3oH